plugins {
    id 'com.android.application'
}

android {
    namespace 'com.tabuadaquest.app'
    compileSdk 35

    defaultConfig {
        applicationId "com.tabuadaquest.app"
        minSdk 23
        targetSdk 35
        versionCode 4
        versionName "1.0.3"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
